# Creating Arrays

In [5]:
import numpy as np

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

# Initial Placeholders

#### Create an array of zeros
* 0을로 이루어진 행열 만들기

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Create an array of ones
* 1로 이루어진 행열 만들기 <br> &nbsp;&nbsp;&nbsp;ex) (2,3,4)이면 3행4열의 행열을 2개 만듦

In [17]:
np.ones((2,3,4), dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

#### Create an array of evenly spaced values (step value) 

In [20]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

#### Create an array of evenly spaced values (number of samples)


In [30]:
# 0~2까지의 범위를 9개의 숫자로 나눈다
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#### Create a constant array

In [28]:
# 2행 2열의 형열을 만들고 7로 채움
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

#### Create a 2X2 identity matrix
* 2x2 단위행열

In [27]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

#### Create an array with random values
* 난수발생 행열

In [32]:
np.random.random((2,2))

array([[0.54159107, 0.25350827],
       [0.94213552, 0.7724979 ]])

#### Create an empty array

In [33]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# Data Types

#### Signed 64-bit integer types

In [34]:
np.int64

numpy.int64

#### Standard double-precision floating point

In [36]:
np.float32

numpy.float32

#### Complex numbers represented by 128 floats

In [38]:
np.complex

complex

#### Boolean type strong *True* and *False* values

In [40]:
np.bool

bool

#### Python object type

In [42]:
np.object

object

#### Fixed-length string type

In [45]:
np.string_

numpy.bytes_

#### Fixed-length unicode type

In [47]:
np.unicode_

numpy.str_

# Inspecting your array

#### Array dimensions

In [49]:
a.shape

(1, 3)